# NOTE: leave empty if you want to use a flat-file database (stores data to a .txt file) or sqlite (stores data to a .db file)
host: ""
port: ""
database-name: "" # only for SQL type database [POSTGRESQL, MySQL]
user: ""
password: ""

# whether to use a flat-file database or redis database
# (use and fill credentials above to use a redis or any SQL database)
# database:  'sqlite' or 'redis' or 'flat-file' or 'mongodb' or 'postgresql'
# default: 'sqlite'
database-type: 'sqlite'

# in ticks (millis). 6000 - 5 mins. 20 * 60 = 1200 (60 seconds) * 5 = 6000 milliseconds.
# default: 6000
database-save-delay: 6000

# in minecraft ticks (millis). delay between getting nearby players. 20 * 3 = 60 (3 seconds)
# default: 60
nearby-get-delay: 60

# block radius to check for nearby players for nearchat.
# default: 30
near-block-radius: 30

# check whether to log nearchat messages to console.
# default: true
log-messages: true

# the delay (in seconds) to wait until you can chat on NearChat upon logging in.
# default: 3
delay-time: 3
delay: true